import './setup.ts';
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import type { WindHistoryEvent, WindProjectInput } from '@aihot/contracts/wind';
import { classifyProgress } from '@aihot/backend/projects/identity';
import { matchProjects } from '@aihot/backend/projects/rules';
import { identifyProgress, progressInbox, windProgress } from '@aihot/backend/projects/progress';
import { importWindHistory, relinkWindHistory, windHistory } from '@aihot/backend/projects/history';
import { commitWindImport, previewWindImport } from '@aihot/backend/projects/service';
import { closeDb } from '@aihot/backend/db';
import { tag } from './setup.ts';
after(closeDb);
const event = (hint: string, type = '招标'): WindHistoryEvent => ({ projectHint: hint, eventType: type, eventDate: null, summary:'历史记录摘要', sourceName:'', sourceUrl:null, risk:'', suggestedStage:'' });
const p = (id: string, name: string, aliases: string[] = []): WindProjectInput => ({ id, name, aliases, province:'广东', city:'阳江', developer:null, capacityMw:null, enabled:true, priority:'normal' });
test('numbered project identities do not confuse ten with eleven or V with VI', () => {
  const pool = [p('a','阳江三山岛十海上风电项目',['三山岛十']),p('b','阳江三山岛十一海上风电项目',['三山岛十一'])];
  assert.deepEqual(matchProjects('阳江三山岛十一海上风电项目',pool),['b']);
  assert.deepEqual(matchProjects('三山岛十一；另一个三山岛十项目',pool),['a','b']);
  assert.deepEqual(matchProjects('青洲VI项目',[p('v','阳江青洲V海上风电项目',['青洲V']),p('vi','阳江青洲VI海上风电项目',['青洲VI'])]),['vi']);
  assert.deepEqual(matchProjects('阳江帆石二1000MW海上风电项目',[p('fs2','阳江帆石二海上风电项目',['帆石二'])]),['fs2']);
  assert.deepEqual(matchProjects('大丰H19项目',[p('h1','大丰H1项目',['大丰H1']),p('h19','大丰H19项目',['大丰H19'])]),['h19']);
});
test('clear out-of-registry identities, policy and capacity-only reports have different reasons', () => {
  assert.equal(classifyProgress(event('华能射阳南区H6#海上风电项目'),[]).kind,'missing_project');
  assert.equal(classifyProgress(event('浙江省内规模约501MW的海上风电项目，具体项目名称待核验'),[]).kind,'unknown');
  assert.equal(classifyProgress(event('华润在江苏开发的408MW海上风电项目，场址待核验'),[]).kind,'unknown');
  assert.equal(classifyProgress(event('全国海上风电产业规模与十五五规划','政策变化'),[]).kind,'policy');
  const pool=[p('actual','测试海上风电项目'),p('DEMO-x','示例海上风电项目')];
  assert.equal(classifyProgress(event('测试海上风电项目'),pool).kind,'matched');
  assert.equal(classifyProgress(event('示例海上风电项目'),pool).kind,'missing_project');
});
test('joint identity enrichment waits for every project and never erases original archive or notification', async () => {
  const t=tag(), actor=`test:${t}`, names=[`测试${t}甲海上风电项目`,`测试${t}乙海上风电项目`];
  await importWindHistory({records:[{origin:'gmail', externalId:t, title:'未知容量标题', body:JSON.stringify([{project_hint:'1528MW未知项目',summary:'原摘要，不自动作为当前事实',event_type:'延期'}]),sentRecord:true}]},actor);
  const archive=(await windHistory()).find(r=>r.externalId===t)!;
  const input={projectNames:names,reason:'原公告明确列出两个项目。',evidenceUrl:'https://example.com/joint-notice'};
  await identifyProgress(archive.id,0,input,actor);
  const a=p(`IDENTITY-${t}-a`,names[0]),b=p(`IDENTITY-${t}-b`,names[1]);
  let preview=await previewWindImport({projects:[a]});await commitWindImport({projects:[a],token:preview.token},actor);
  assert.equal((await windProgress([a.id])).length,0,'partial registry must not lose the other project');
  const entry=(await progressInbox()).find(e=>e.historyId===archive.id)!;
  assert.equal(entry.resolution.kind,'missing_project');assert.deepEqual(entry.resolution.projectNames,names);
  preview=await previewWindImport({projects:[b]});await commitWindImport({projects:[b],token:preview.token},actor);
  assert.equal((await windProgress([a.id])).length,1);assert.equal((await windProgress([b.id])).length,1);
  assert.equal((await progressInbox()).some(e=>e.historyId===archive.id),false);
  const after=(await windHistory('',null,archive.id))[0];assert.equal(after.body,archive.body);assert.equal(after.notification,'sent_record');
  await assert.rejects(identifyProgress(archive.id,0,{...input,projectNames:[]},actor),/格式/);
  await assert.rejects(identifyProgress(archive.id,0,{...input,evidenceUrl:'file:///etc/passwd'},actor),/网址/);
  await relinkWindHistory(actor);
});
